@echo off
cd /d "%~dp0"
echo Pulling latest code...
git pull origin RSS-Generator-IONOS
echo Stopping containers...
docker compose down
echo Building...
docker compose build
echo Starting...
docker compose up -d
echo Done. Showing logs (Ctrl+C to stop):
docker compose logs -f
