import { useState } from 'react'
import { Input } from '../ui/Input'
import { Toggle } from '../ui/Toggle'
import { Button } from '../ui/Button'
import { Tooltip } from '../ui/Tooltip'
import { ErrorBanner } from '../ui/ErrorBanner'
import { VisualPicker } from './VisualPicker'
import type { FeedConfigCreate } from '../../api/types'

interface FeedFormProps {
  initialValues?: Partial<FeedConfigCreate>
  onSubmit: (data: FeedConfigCreate) => void
  isLoading?: boolean
  submitLabel?: string
  error?: string
  /** Called when "Test Selectors" is clicked — only available in edit mode */
  onPreview?: () => void
  isPreviewing?: boolean
  /** When set, applied as the form's id and the internal action buttons are hidden */
  formId?: string
}

/** Convert a simple CSS selector (as generated by the visual picker) to an XPath expression.
 *  relative=true  → prepend '.'  (for field selectors relative to a container)
 *  relative=false → absolute expression starting with '//' */
function cssToXPath(css: string, relative: boolean): string {
  // Handle comma-separated multi-selectors → XPath union operator
  const alternatives = css.split(/\s*,\s*/).map(s => s.trim()).filter(Boolean)
  if (alternatives.length > 1) {
    return alternatives.map(s => cssToXPath(s, relative)).join(' | ')
  }

  const prefix = relative ? '.' : ''
  const parts: string[] = []

  // Split on ' > ' (child combinator) first, then on whitespace (descendant)
  const segments = css.split(/\s*>\s*/)
  segments.forEach((seg, segIdx) => {
    seg.trim().split(/\s+/).forEach((rawPart, partIdx) => {
      // Extract :nth-of-type(N) before stripping pseudo-classes
      const nthMatch = rawPart.match(/:nth-of-type\((\d+)\)/)
      const nthPos = nthMatch ? parseInt(nthMatch[1]) : null
      // Strip pseudo-classes like :nth-of-type(2), :not(...)
      const part = rawPart.replace(/:[a-z-]+(\([^)]*\))?/gi, '').trim()
      if (!part) return

      const tagMatch = part.match(/^([a-zA-Z][a-zA-Z0-9]*|\*)/)
      const tag = tagMatch?.[1] ?? '*'
      const classes = [...part.matchAll(/\.([a-zA-Z0-9_-]+)/g)].map(m => m[1])
      const idMatch = part.match(/#([a-zA-Z0-9_-]+)/)

      const conds: string[] = []
      if (idMatch) conds.push(`@id='${idMatch[1]}'`)
      classes.forEach(c => conds.push(`contains(@class, '${c}')`))

      const node = tag + (conds.length ? `[${conds.join(' and ')}]` : '') + (nthPos !== null ? `[${nthPos}]` : '')
      const isFirst = segIdx === 0 && partIdx === 0
      // child combinator (>) → single slash; descendant (space) → double slash
      const sep = isFirst ? '//' : (partIdx === 0 ? '/' : '//')
      parts.push(sep + node)
    })
  })

  return prefix + parts.join('')
}

function slugify(s: string) {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

export function FeedForm({
  initialValues,
  onSubmit,
  isLoading,
  submitLabel = 'Create Feed',
  error,
  onPreview,
  isPreviewing,
  formId,
}: FeedFormProps) {
  const [form, setForm] = useState<FeedConfigCreate>({
    slug: initialValues?.slug ?? '',
    url: initialValues?.url ?? '',
    title: initialValues?.title ?? '',
    description: initialValues?.description ?? '',
    // CSS
    selector_item: initialValues?.selector_item ?? '',
    selector_title: initialValues?.selector_title ?? '',
    selector_link: initialValues?.selector_link ?? '',
    selector_link_attr: initialValues?.selector_link_attr ?? 'href',
    selector_description: initialValues?.selector_description ?? '',
    selector_date: initialValues?.selector_date ?? '',
    selector_author: initialValues?.selector_author ?? '',
    selector_item_excluded: initialValues?.selector_item_excluded ?? undefined,
    date_format: initialValues?.date_format ?? '',
    // XPath
    use_xpath: initialValues?.use_xpath ?? true,
    xpath_item: initialValues?.xpath_item ?? '',
    xpath_title: initialValues?.xpath_title ?? '',
    xpath_link: initialValues?.xpath_link ?? '',
    xpath_link_attr: initialValues?.xpath_link_attr ?? 'href',
    xpath_description: initialValues?.xpath_description ?? '',
    xpath_date: initialValues?.xpath_date ?? '',
    xpath_author: initialValues?.xpath_author ?? '',
    // Options
    poll_interval_minutes: initialValues?.poll_interval_minutes ?? 60,
    use_playwright: initialValues?.use_playwright ?? false,
    keep_html: initialValues?.keep_html ?? false,
    label: initialValues?.label ?? '',
  })

  const [slugManuallyEdited, setSlugManuallyEdited] = useState(!!initialValues?.slug)
  const [showAdvanced, setShowAdvanced] = useState(
    !!(initialValues?.selector_description || initialValues?.selector_date || initialValues?.selector_author
      || initialValues?.xpath_description || initialValues?.xpath_date || initialValues?.xpath_author),
  )
  const [showPicker, setShowPicker] = useState(false)
  // Tracks the last picker state (even if closed without Apply) so it's restored on re-open
  const [pickerSelectors, setPickerSelectors] = useState<import('./VisualPicker').PickerSelectors>({
    selector_item:        initialValues?.selector_item        || undefined,
    selector_title:       initialValues?.selector_title       || undefined,
    selector_link:        initialValues?.selector_link        || undefined,
    selector_description: initialValues?.selector_description || undefined,
    selector_date:        initialValues?.selector_date        || undefined,
    selector_author:      initialValues?.selector_author      || undefined,
    selector_item_excluded: initialValues?.selector_item_excluded || undefined,
  })

  const set = <K extends keyof FeedConfigCreate>(key: K, value: FeedConfigCreate[K]) =>
    setForm((f) => ({ ...f, [key]: value }))

  const handleTitleChange = (title: string) => {
    set('title', title)
    if (!slugManuallyEdited) set('slug', slugify(title))
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    const cleaned: FeedConfigCreate = {
      ...form,
      selector_description: form.selector_description || undefined,
      selector_date: form.selector_date || undefined,
      selector_author: form.selector_author || undefined,
      date_format: form.date_format || undefined,
      xpath_item: form.xpath_item || undefined,
      xpath_title: form.xpath_title || undefined,
      xpath_link: form.xpath_link || undefined,
      xpath_description: form.xpath_description || undefined,
      xpath_date: form.xpath_date || undefined,
      xpath_author: form.xpath_author || undefined,
      selector_item_excluded: form.selector_item_excluded || undefined,
      label: form.label || undefined,
    }
    onSubmit(cleaned)
  }

  const handlePickerComplete = (result: import('./VisualPicker').PickerSelectors) => {
    setShowPicker(false)
    setPickerSelectors(result)

    // Merge picker result directly into form — don't rely on batched set() calls.
    // In XPath mode the picker still produces CSS selectors, so convert them.
    const merged = form.use_xpath
      ? {
          ...form,
          // XPath fields via CSS conversion
          ...(result.selector_item        && { xpath_item:        cssToXPath(result.selector_item, false) }),
          ...(result.selector_title       && { xpath_title:       cssToXPath(result.selector_title, true) }),
          ...(result.selector_link        && { xpath_link:        cssToXPath(result.selector_link, true) }),
          ...(result.selector_description && { xpath_description: cssToXPath(result.selector_description, true) }),
          ...(result.selector_date        && { xpath_date:        cssToXPath(result.selector_date, true) }),
          ...(result.selector_author      && { xpath_author:      cssToXPath(result.selector_author, true) }),
          // Also store raw CSS so picker can restore selections on return
          ...(result.selector_item        && { selector_item:        result.selector_item }),
          ...(result.selector_title       && { selector_title:       result.selector_title }),
          ...(result.selector_link        && { selector_link:        result.selector_link }),
          ...(result.selector_description && { selector_description: result.selector_description }),
          ...(result.selector_date        && { selector_date:        result.selector_date }),
          ...(result.selector_author      && { selector_author:      result.selector_author }),
          // excluded hrefs stored in selector_item_excluded regardless of mode
          ...(result.selector_item_excluded !== undefined && { selector_item_excluded: result.selector_item_excluded }),
        }
      : {
          ...form,
          ...(result.selector_item        && { selector_item:        result.selector_item }),
          ...(result.selector_title       && { selector_title:       result.selector_title }),
          ...(result.selector_link        && { selector_link:        result.selector_link }),
          ...(result.selector_description && { selector_description: result.selector_description }),
          ...(result.selector_date        && { selector_date:        result.selector_date }),
          ...(result.selector_author      && { selector_author:      result.selector_author }),
          ...(result.selector_item_excluded !== undefined && { selector_item_excluded: result.selector_item_excluded }),
        }
    setForm(merged)
    if (result.selector_description || result.selector_date || result.selector_author) {
      setShowAdvanced(true)
    }

    // In edit mode, clicking Save in the picker saves to the server immediately
    if (submitLabel !== 'Create Feed') {
      const cleaned: FeedConfigCreate = {
        ...merged,
        selector_description: merged.selector_description || undefined,
        selector_date:        merged.selector_date        || undefined,
        selector_author:      merged.selector_author      || undefined,
        date_format:          merged.date_format          || undefined,
        xpath_item:           merged.xpath_item           || undefined,
        xpath_title:          merged.xpath_title          || undefined,
        xpath_link:           merged.xpath_link           || undefined,
        xpath_description:    merged.xpath_description    || undefined,
        xpath_date:           merged.xpath_date           || undefined,
        xpath_author:         merged.xpath_author         || undefined,
        selector_item_excluded: merged.selector_item_excluded || undefined,
      }
      onSubmit(cleaned)
    }
  }

  const handlePickerClose = (partial: import('./VisualPicker').PickerSelectors) => {
    setShowPicker(false)
    setPickerSelectors(partial)
  }

  return (
    <>
    {showPicker && (
      <VisualPicker
        url={form.url}
        initialSelectors={pickerSelectors}
        usePlaywright={form.use_playwright}
        onComplete={handlePickerComplete}
        onClose={handlePickerClose}
        onTogglePlaywright={() => set('use_playwright', !form.use_playwright)}
      />
    )}
    <form id={formId} onSubmit={handleSubmit} className="space-y-8">
      {error && <ErrorBanner message={error} />}

      {/* Basic info */}
      <section className="space-y-4">
        <h3 className="text-sm font-semibold uppercase tracking-wide text-gray-400">Basic Info</h3>
        <Input
          label="Title"
          required
          value={form.title}
          onChange={(e) => handleTitleChange(e.target.value)}
          placeholder="My Blog Feed"
        />
        <Input
          label="Slug"
          required
          mono
          value={form.slug}
          onChange={(e) => {
            setSlugManuallyEdited(true)
            set('slug', e.target.value)
          }}
          hint="Used in the feed URL: /feed/{slug}.xml"
          placeholder="my-blog-feed"
        />
        <div className="flex items-end gap-2">
          <div className="flex-1">
            <Input
              label="Source URL"
              required
              type="url"
              value={form.url}
              onChange={(e) => set('url', e.target.value)}
              placeholder="https://example.com/blog"
            />
          </div>
          {form.url && (
            <Button
              type="button"
              variant="outline"
              size="md"
              onClick={() => setShowPicker(true)}
              title="Open the page and click to pick CSS selectors visually"
            >
              Visual Picker
            </Button>
          )}
        </div>
        <Input
          label="Description"
          value={form.description ?? ''}
          onChange={(e) => set('description', e.target.value)}
          placeholder="A short description of this feed"
        />
        <Input
          label="Label"
          value={form.label ?? ''}
          onChange={(e) => set('label', e.target.value)}
          placeholder="e.g. Tech, Marketing, News"
          hint="Optional. Used to group feeds on the main page."
        />
      </section>

      {/* Selector mode toggle + fields */}
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-semibold uppercase tracking-wide text-gray-400">
            {form.use_xpath ? 'XPath Selectors' : 'CSS Selectors'}
          </h3>
          <div className="flex items-center gap-2">
            <span className={`text-xs font-medium ${!form.use_xpath ? 'text-orange-600' : 'text-gray-400'}`}>CSS</span>
            <button
              type="button"
              role="switch"
              aria-checked={form.use_xpath}
              onClick={() => set('use_xpath', !form.use_xpath)}
              className={`relative inline-flex h-5 w-9 items-center rounded-full transition-colors focus:outline-none ${
                form.use_xpath ? 'bg-orange-500' : 'bg-gray-300'
              }`}
            >
              <span
                className={`inline-block h-3.5 w-3.5 transform rounded-full bg-white shadow transition-transform ${
                  form.use_xpath ? 'translate-x-4' : 'translate-x-1'
                }`}
              />
            </button>
            <span className={`text-xs font-medium ${form.use_xpath ? 'text-orange-600' : 'text-gray-400'}`}>XPath</span>
          </div>
        </div>

        {!form.use_xpath ? (
          <>
            {/* CSS required fields */}
            <div className="flex items-end gap-2">
              <div className="flex-1">
                <Input
                  label="Item container"
                  required
                  mono
                  value={form.selector_item}
                  onChange={(e) => set('selector_item', e.target.value)}
                  placeholder="article.post"
                />
              </div>
              <Tooltip content="CSS selector for the repeating container of each item. e.g. 'article.post', 'ul.feed > li'" />
            </div>

            <div className="flex items-end gap-2">
              <div className="flex-1">
                <Input
                  label="Title"
                  required
                  mono
                  value={form.selector_title}
                  onChange={(e) => set('selector_title', e.target.value)}
                  placeholder="h2 a"
                />
              </div>
              <Tooltip content="CSS selector for the title, relative to the item container. e.g. 'h2', '.post-title a'" />
            </div>

            {/* CSS optional selectors */}
            <button
              type="button"
              onClick={() => setShowAdvanced(!showAdvanced)}
              className="text-xs font-medium text-orange-600 hover:underline"
            >
              {showAdvanced ? '▾ Hide optional selectors' : '▸ Show optional selectors'}
            </button>

            {showAdvanced && (
              <div className="space-y-4 rounded-md border border-gray-200 p-4">
                <div className="flex items-end gap-2">
                  <div className="flex-1">
                    <Input
                      label="Description"
                      mono
                      value={form.selector_description ?? ''}
                      onChange={(e) => set('selector_description', e.target.value)}
                      placeholder="p.summary"
                    />
                  </div>
                  <Tooltip content="Optional. CSS selector for the item description/summary text." />
                </div>

                <div className="flex items-end gap-2">
                  <div className="flex-1">
                    <Input
                      label="Author"
                      mono
                      value={form.selector_author ?? ''}
                      onChange={(e) => set('selector_author', e.target.value)}
                      placeholder=".author-name"
                    />
                  </div>
                  <Tooltip content="Optional. CSS selector for the author name." />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div className="flex items-end gap-2">
                    <div className="flex-1">
                      <Input
                        label="Date"
                        mono
                        value={form.selector_date ?? ''}
                        onChange={(e) => set('selector_date', e.target.value)}
                        placeholder="time"
                      />
                    </div>
                    <Tooltip content="Optional. CSS selector for the publication date element. Works with <time datetime='...'> automatically." />
                  </div>
                  <Input
                    label="Date format"
                    mono
                    value={form.date_format ?? ''}
                    onChange={(e) => set('date_format', e.target.value)}
                    placeholder="%Y-%m-%d"
                    hint="strptime format. Leave blank for auto-detect."
                  />
                </div>

                <div className="grid grid-cols-3 gap-3 border-t border-gray-100 pt-4">
                  <div className="col-span-2 flex items-end gap-2">
                    <div className="flex-1">
                      <Input
                        label="Link (auto-detected if empty)"
                        mono
                        value={form.selector_link ?? ''}
                        onChange={(e) => set('selector_link', e.target.value)}
                        placeholder="a.read-more"
                        hint="Leave blank to use the first <a href> in each article."
                      />
                    </div>
                    <Tooltip content="Override the auto-detected link selector. Relative to item container." />
                  </div>
                  <Input
                    label="Link attribute"
                    mono
                    value={form.selector_link_attr}
                    onChange={(e) => set('selector_link_attr', e.target.value)}
                    placeholder="href"
                  />
                </div>
              </div>
            )}
          </>
        ) : (
          <>
            {/* XPath required fields */}
            <div className="flex items-end gap-2">
              <div className="flex-1">
                <Input
                  label="Item container"
                  required
                  mono
                  value={form.xpath_item ?? ''}
                  onChange={(e) => set('xpath_item', e.target.value)}
                  placeholder="//article"
                />
              </div>
              <Tooltip content="XPath for the repeating container of each item. e.g. '//article' or '//ul[@class=&quot;feed&quot;]/li'" />
            </div>

            <div className="flex items-end gap-2">
              <div className="flex-1">
                <Input
                  label="Title"
                  required
                  mono
                  value={form.xpath_title ?? ''}
                  onChange={(e) => set('xpath_title', e.target.value)}
                  placeholder=".//h2"
                />
              </div>
              <Tooltip content="XPath relative to each container. e.g. './/h2' or './/a[@class=&quot;title&quot;]'" />
            </div>

            {/* XPath optional selectors */}
            <button
              type="button"
              onClick={() => setShowAdvanced(!showAdvanced)}
              className="text-xs font-medium text-orange-600 hover:underline"
            >
              {showAdvanced ? '▾ Hide optional selectors' : '▸ Show optional selectors'}
            </button>

            {showAdvanced && (
              <div className="space-y-4 rounded-md border border-gray-200 p-4">
                <div className="flex items-end gap-2">
                  <div className="flex-1">
                    <Input
                      label="Description"
                      mono
                      value={form.xpath_description ?? ''}
                      onChange={(e) => set('xpath_description', e.target.value)}
                      placeholder=".//p[@class='summary']"
                    />
                  </div>
                  <Tooltip content="Optional. XPath for the description element, relative to container." />
                </div>

                <div className="flex items-end gap-2">
                  <div className="flex-1">
                    <Input
                      label="Author"
                      mono
                      value={form.xpath_author ?? ''}
                      onChange={(e) => set('xpath_author', e.target.value)}
                      placeholder=".//span[@class='author']"
                    />
                  </div>
                  <Tooltip content="Optional. XPath for the author element, relative to container." />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div className="flex items-end gap-2">
                    <div className="flex-1">
                      <Input
                        label="Date"
                        mono
                        value={form.xpath_date ?? ''}
                        onChange={(e) => set('xpath_date', e.target.value)}
                        placeholder=".//time"
                      />
                    </div>
                    <Tooltip content="Optional. XPath for the date element. Works with <time datetime='...'> automatically." />
                  </div>
                  <Input
                    label="Date format"
                    mono
                    value={form.date_format ?? ''}
                    onChange={(e) => set('date_format', e.target.value)}
                    placeholder="%Y-%m-%d"
                    hint="strptime format. Leave blank for auto-detect."
                  />
                </div>

                <div className="grid grid-cols-3 gap-3 border-t border-gray-100 pt-4">
                  <div className="col-span-2 flex items-end gap-2">
                    <div className="flex-1">
                      <Input
                        label="Link (auto-detected if empty)"
                        mono
                        value={form.xpath_link ?? ''}
                        onChange={(e) => set('xpath_link', e.target.value)}
                        placeholder=".//a"
                        hint="Leave blank to use the first <a href>. Use .//a/@href to point directly to the attribute."
                      />
                    </div>
                    <Tooltip content="XPath for the link element or attribute. Relative to container." />
                  </div>
                  <Input
                    label="Link attribute"
                    mono
                    value={form.xpath_link_attr ?? 'href'}
                    onChange={(e) => set('xpath_link_attr', e.target.value)}
                    placeholder="href"
                  />
                </div>
              </div>
            )}
          </>
        )}
      </section>

      {/* Options */}
      <section className="space-y-4">
        <h3 className="text-sm font-semibold uppercase tracking-wide text-gray-400">Options</h3>
        <Input
          label="Poll interval (minutes)"
          type="number"
          min={5}
          value={form.poll_interval_minutes}
          onChange={(e) => set('poll_interval_minutes', Number(e.target.value))}
        />
        <Toggle
          label="Keep HTML in description"
          description="Preserve HTML tags in description. Some feed readers render them."
          checked={form.keep_html ?? false}
          onChange={(v) => set('keep_html', v)}
        />
      </section>

      {!formId && (
        <div className="flex items-center gap-3">
          <Button type="submit" loading={isLoading}>
            {submitLabel}
          </Button>
          {onPreview && (
            <Button type="button" variant="outline" onClick={onPreview} loading={isPreviewing}>
              Test Selectors
            </Button>
          )}
        </div>
      )}
    </form>
    </>
  )
}
